server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-cool-silence-aityg9yl-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_7fBkOU6QsGZz}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

app:
  jwt:
    secret: ${APP_JWT_SECRET:dev-secret-change-me-please-use-a-long-random-value-for-production}
    expirationMinutes: 120
  storage:
    path: ${APP_STORAGE_PATH:./uploads}
